apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quickstart-chat
  labels:
    app: quickstart-chat
spec:
  ingressClassName: cloudflare-tunnel
  rules:
    - host: quickstart-chat.jeammm.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quickstart-chat
                port:
                  number: 80
